[package]
name = "HyperFillContracts"
version = "1.0.0"
authors = ["HyperFill Team"]

[addresses]
hyperfill = "0xe22a7dbf85b88f1c950b96923e29f0213121002f296c0572549f2a6a7e7fd6f5"

[dev-addresses]
hyperfill = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]