[package]
name = "hypermove_vault"
version = "1.0.0"
authors = ["HyperMove Team"]

[addresses]
hypermove_vault = "96d2b185a5b581f98dc1df57b59a5875eb53b3a65ef7a9b0d5e42aa44c3b8b82"

[dev-addresses]
hypermove_vault = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"