[package]
name = "hypermove_vault"
version = "1.0.0"
authors = ["HyperMove Team"]

[addresses]
hypermove_vault = "0xc4bd839f1b57aaf6daa5feefab82f3b6b78b4fe0aa2971b9de2a9297878bc576"

[dev-addresses]
hypermove_vault = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"